services:
  app:
    image: starducktea/nfo-translator:latest
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
      - ./reserved.txt:/app/reserved.txt
    environment:
      - PUID=1000
      - PGID=100
      - API_KEY=<YOUR_API_KEY>
      - TRANS_MODE=s2t
      - DATABASE_URL=postgresql://<POSTGRES_USER>:<POSTGRES_PASS>@db:5432/<POSTGRES_DB>